% Mante Default params
%
% Houses default parameters if one runs the Main script in standalone mode.
% Separating this into a separate file, I find, makes it easier to read the
% Main.m code: One can keep this open in a separate pane/window, while reading
% through.

%% GENERAL PROPERTIES
  % Model Resolution/Precision
  dt            = 2e-4;   ... Model bin size
  bin_t         = 5e-2;   ... How to bin post hoc for analysis
  % Model noise
  sigma         = 0.1;    ... Amount of constant noise to add to firing

%% TASK PARAMETERS
  % General Trial Controls
  nTrials       = 5;
  trialDuration = 3;
  % General Stimulus
  iFrac         = 0.33; ... Randomly select a third of the population for a stimulus to receive
  % Context Stimulus
  context_trialStart = 0.3; ...
  context_trialEnd = 1.1; ...
  % Color Motion Stimulus
  color_trialStart =  0.35; ...
  color_trialEnd = 1.1; ...
  % Dot Color Stimulus
  dot_trialStart =  0.35; ...
  dot_trialEnd =  1.1; ...

%% NEURAL NETWORK PARAMETERS---
%  Number of neurons of each type
nInh =       1; ...
nExc =       40; ...
%  Neural Properties
rMax0E =     100; ...
rMax0I =     200; ...
p0E =        0.3; ...
p0I =        0.1; ...
% Time Constants
tausE =      0.025; ...
tausI =      0.005; ...
tauDbar =    0.025; ...
tauDvar =    0;     ...
tauM =       0.010; ...
%  Input Properties
IwidthE =    3; %
IthE =       18; %
IwidthI =    5; %
IthI =       20; %
%  Connection Properties
Wrecurrent=     200; %
sigmaWEE=       0; %
sigmaWasym=     0; %
WIEval=         -320; %
sigmaIE=        0;
