% PE_ManteMain -- Parameter Explorer (PE) Script
%
% This script calls a parameter exploration class I wrote that can either
% check all combinations of a particular parameter set or explore all
% possible combinations.
%
% The main benefits :
% (A) Executes each parameter combination in parallel on a separate core,
%       so it explores much faster on a single computer.
% (B) Saves progress, automatically, so that if it stops 12 out of 80
%       simulations deep for any reason, it picks its progress back up,
%       skipping completed sets.
% (C) Contains a framework for automatically placing results into a nested
%       hierarchy of folders that represent the distinct combination per
%       set.
% (D) Records whatever is printed in the console during a sim to respective
%       folder.
% (E) Other constants that currently are not changing parameters can be given,
%       and PE will record them in the project directory, so you never run a sim
%       with a static parameter that you later change, and forget its value.

%% Script and Project Location
% Declare the script we will iterate through, the folder to store resultant
% sims, and (optionally), a session ID to assign to each completed sim (one will
% be randomly created if not).
scriptname      = 'DFS_ChoiceCoherence';
projectfolder   ='~/Data/Miller/FindNetTone';

%% Variables
% Set parameters -- the space over which all value combinations explored
param = struct( ...
        
	);

% Set constants -- this variable space remains the same for each script run
% ...BUT are each actually documented in the containing folder, for the
% purpose that we may later choose to vary them!
consts = struct( ...
        ... Model Resolution/Precision
        'dt',    2e-4, ... Model bin size
        'bin_t', 5e-2, ... How to bin post hoc for analysis
        ... Model noise
        'sigma', 0.1,    ...
    ... ---TASK PARAMETERS---
        ... General Trial Controls
        'nTrials',       5, ...
        'trialDuration', 3, ...
        ... General Stimulus
        'iFrac',         0.33, ...   Randomly select a third of the population for a stimulus to receive
        ... Context Stimulus
        'context_trialStart',    0.3, ...
        'context_trialEnd',      1.1, ...
        ... Color Motion Stimulus
        'color_trialStart',      0.35, ...
        'color_trialEnd',        1.1, ...
        ... Dot Color Stimulus
        'dot_trialStart',        0.35, ...
        'dot_trialEnd',          1.1, ...
    ... ---NEURAL NETWORK PARAMETERS---
        ... Number of neurons of each type
        'nInh',      1, ...
        'nExc',      40, ...
        ... Neural Properties
        'rMax0E',    100, ...
        'rMax0I',    200, ...
        'p0E',       0.3, ...
        'p0I',       0.1, ...
        ...Time Constants
        'tausE',     0.025, ...
        'tausI',     0.005, ...
        'tauDbar',   0.025, ...
        'tauDvar',   0,     ...
        'tauM',      0.010, ...
        ... Input Properties
        'IwidthE',   3, ...
        'IthE',      18, ...
        'IwidthI',   5, ...
        'IthI',      20, ...
        ... Connection Properties
        'Wrecurrent',    200, ...
        'sigmaWEE',      0, ...
        'sigmaWasym',    0, ...
        'WIEval',        -320, ...
        'sigmaIE',       0 ...
    );

%% Create Explorer, Set Options`

% Run the parameter explorer for with reward versus not reward conditions!
Explorer = ParameterExplorer(scriptname,param,...
    'projectfolder',projectfolder,'consts',consts);
% Set options to run with, one specifying that, yes, we will run in
% parallel; the other, that jobs ought be deleted after they're finished
Explorer.useparallel    = true;
Explorer.deletejobs     = true;

%% RUN!
Explorer.run();
